require 'pathname'

module CedarTargetFailing_OS_X_Test_Bundle
  SPECS_TARGET_NAME = "Failing OS X Host App"
  CONFIGURATION = "Release"

  PROJECT_ROOT = Pathname.new(File.dirname(__FILE__)).parent.to_s
  BUILD_DIR = File.join(PROJECT_ROOT, "build")

  FileUtils.mkdir_p(File.join(BUILD_DIR, CONFIGURATION))

  class << self
    def in_project_dir
      original_dir = Dir.pwd
      Dir.chdir(PROJECT_ROOT)

      yield

      ensure
      Dir.chdir(original_dir)
    end

    def build_dir
      File.join(BUILD_DIR, CONFIGURATION)
    end

    def system_or_exit(cmd, stdout = nil)
      puts "Executing #{cmd}"
      cmd += " >#{stdout}" if stdout
      system(cmd) or raise "******** Build failed ********"
    end

    def run_cmd_and_grep_for_failure(cmd)
      puts "Executing #{cmd}"
      puts result = %x[#{cmd} 2>&1]
      if !result.index(/examples, 0 failures/)
        exit(1)
      end
    end

    def with_env_vars(env_vars)
      old_values = {}
      env_vars.each do |key,new_value|
        old_values[key] = ENV[key]
        ENV[key] = new_value
      end

      yield

      env_vars.each_key do |key|
        ENV[key] = old_values[key]
      end
    end

    def output_file(target)
      output_dir = if ENV['IS_CI_BOX']
        ENV['CC_BUILD_ARTIFACTS']
      else
        Dir.mkdir(BUILD_DIR) unless File.exists?(BUILD_DIR)
        BUILD_DIR
      end

      output_file = File.join(output_dir, "#{target}.output")
      puts "Output: #{output_file}"
      output_file
    end
  end
end

desc "Clean build directory"
task :clean_Failing_OS_X_Test_Bundle do
  CedarTargetFailing_OS_X_Test_Bundle.system_or_exit "rm -rf #{CedarTargetFailing_OS_X_Test_Bundle::BUILD_DIR}/*", CedarTargetFailing_OS_X_Test_Bundle.output_file("clean")
end

desc "Build and run Failing_OS_X_Test_Bundle OCUnit logic specs"
task :Failing_OS_X_Test_Bundle => :clean_Failing_OS_X_Test_Bundle do
  build_and_test_command = <<END_SHELL_CMD
      xcodebuild -scheme #{CedarTargetFailing_OS_X_Test_Bundle::SPECS_TARGET_NAME} -configuration Debug -arch x86_64 clean test SYMROOT='#{CedarTargetFailing_OS_X_Test_Bundle::BUILD_DIR}'
END_SHELL_CMD
  CedarTargetFailing_OS_X_Test_Bundle.in_project_dir do
    CedarTargetFailing_OS_X_Test_Bundle.run_cmd_and_grep_for_failure build_and_test_command
  end
end
